<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "DTD/xhtml1-frameset.dtd">
<html>
<head>
 <title><?php echo _("Help") ?></title>
</head>

<frameset rows="30,*" frameborder="no" border="0" framespacing="0">
 <frame name="help_menu" scrolling="no" marginheight="0" marginwidth="0" src="<?php echo $menu_url ?>" />
 <frame name="help_main" resizeable="yes" marginheight="2" marginwidth="2" src="<?php echo $main_url ?>" />
</frameset>

</html>
