// I18N constants

// LANG: "en", ENCODING: UTF-8 | ISO-8859-1
// Author: Mihai Bazon, http://dynarch.com/mishoo

// FOR TRANSLATORS:
//
//   1. PLEASE PUT YOUR CONTACT INFO IN THE ABOVE LINE
//      (at least a valid email address)
//
//   2. PLEASE TRY TO USE UTF-8 FOR ENCODING;
//      (if this is not possible, please include a comment
//       that states what encoding is necessary.)

TableOperations.I18N = {
	"Align":					  "<?php echo addslashes(_("Align")) ?>",
	"All four sides":				  "<?php echo addslashes(_("All four sides")) ?>",
	"Background":					  "<?php echo addslashes(_("Background")) ?>",
	"Baseline":                                       "<?php echo addslashes(_("Baseline")) ?>",
	"Border":					  "<?php echo addslashes(_("Border")) ?>",
	"Borders":					  "<?php echo addslashes(_("Borders")) ?>",
	"Bottom":                                         "<?php echo addslashes(_("Bottom")) ?>",
	"CSS Style":					  "<?php echo addslashes(_("Style [CSS]")) ?>",
	"Caption":					  "<?php echo addslashes(_("Caption")) ?>",
	"Cell Properties":                                "<?php echo addslashes(_("Cell Properties")) ?>",
	"Center":					  "<?php echo addslashes(_("Center")) ?>",
	"Char":                                           "<?php echo addslashes(_("Char")) ?>",
	"Collapsed borders":                              "<?php echo addslashes(_("Collapsed borders")) ?>",
	"Color":					  "<?php echo addslashes(_("Color")) ?>",
	"Description":					  "<?php echo addslashes(_("Description")) ?>",
	"FG Color":					  "<?php echo addslashes(_("FG Color")) ?>",
	"Float":                                          "<?php echo addslashes(_("Float")) ?>",
	"Frames":					  "<?php echo addslashes(_("Frames")) ?>",
	"Height":                                         "<?php echo addslashes(_("Height")) ?>",
	"How many columns would you like to merge?":      "<?php echo addslashes(_("How many columns would you like to merge?")) ?>",
	"How many rows would you like to merge?":         "<?php echo addslashes(_("How many rows would you like to merge?")) ?>",
	"Image URL":					  "<?php echo addslashes(_("Image URL")) ?>",
	"Justify":                                        "<?php echo addslashes(_("Justify")) ?>",
	"Layout":					  "<?php echo addslashes(_("Layout")) ?>",
	"Left":						  "<?php echo addslashes(_("Left")) ?>",
	"Margin":                                         "<?php echo addslashes(_("Margin")) ?>",
	"Middle":                                         "<?php echo addslashes(_("Middle")) ?>",
	"No rules":					  "<?php echo addslashes(_("No rules")) ?>",
	"No sides":					  "<?php echo addslashes(_("No sides")) ?>",
	"None":                                           "<?php echo addslashes(_("None")) ?>",
	"Padding":					  "<?php echo addslashes(_("Padding")) ?>",
	"Please click into some cell":                    "<?php echo addslashes(_("Please click into some cell")) ?>",
	"Right":					  "<?php echo addslashes(_("Right")) ?>",
	"Row Properties":                                 "<?php echo addslashes(_("Row Properties")) ?>",
	"Rules will appear between all rows and columns": "<?php echo addslashes(_("Rules will appear between all rows and columns")) ?>",
	"Rules will appear between columns only":	  "<?php echo addslashes(_("Rules will appear between columns only")) ?>",
	"Rules will appear between rows only":		  "<?php echo addslashes(_("Rules will appear between rows only")) ?>",
	"Rules":					  "<?php echo addslashes(_("Rules")) ?>",
	"Spacing and padding":                            "<?php echo addslashes(_("Spacing and padding")) ?>",
	"Spacing":					  "<?php echo addslashes(_("Spacing")) ?>",
	"Summary":					  "<?php echo addslashes(_("Summary")) ?>",
	"TO-cell-delete":				  "<?php echo addslashes(_("Delete cell")) ?>",
	"TO-cell-insert-after":				  "<?php echo addslashes(_("Insert cell after")) ?>",
	"TO-cell-insert-before":			  "<?php echo addslashes(_("Insert cell before")) ?>",
	"TO-cell-merge":				  "<?php echo addslashes(_("Merge cells")) ?>",
	"TO-cell-prop":					  "<?php echo addslashes(_("Cell properties")) ?>",
	"TO-cell-split":				  "<?php echo addslashes(_("Split cell")) ?>",
	"TO-col-delete":				  "<?php echo addslashes(_("Delete column")) ?>",
	"TO-col-insert-after":				  "<?php echo addslashes(_("Insert column after")) ?>",
	"TO-col-insert-before":				  "<?php echo addslashes(_("Insert column before")) ?>",
	"TO-col-split":					  "<?php echo addslashes(_("Split column")) ?>",
	"TO-row-delete":				  "<?php echo addslashes(_("Delete row")) ?>",
	"TO-row-insert-above":				  "<?php echo addslashes(_("Insert row before")) ?>",
	"TO-row-insert-under":				  "<?php echo addslashes(_("Insert row after")) ?>",
	"TO-row-prop":					  "<?php echo addslashes(_("Row properties")) ?>",
	"TO-row-split":					  "<?php echo addslashes(_("Split row")) ?>",
	"TO-table-prop":				  "<?php echo addslashes(_("Table properties")) ?>",
	"Table Properties":				  "<?php echo addslashes(_("Table Properties")) ?>",
	"Text align":                                     "<?php echo addslashes(_("Text align")) ?>",
	"The bottom side only":				  "<?php echo addslashes(_("The bottom side only")) ?>",
	"The left-hand side only":			  "<?php echo addslashes(_("The left-hand side only")) ?>",
	"The right and left sides only":		  "<?php echo addslashes(_("The right and left sides only")) ?>",
	"The right-hand side only":			  "<?php echo addslashes(_("The right-hand side only")) ?>",
	"The top and bottom sides only":		  "<?php echo addslashes(_("The top and bottom sides only")) ?>",
	"The top side only":				  "<?php echo addslashes(_("The top side only")) ?>",
	"Top":                                            "<?php echo addslashes(_("Top")) ?>",
	"Unset color":                                    "<?php echo addslashes(_("Unset color")) ?>",
	"Vertical align":                                 "<?php echo addslashes(_("Vertical align")) ?>",
	"Width":					  "<?php echo addslashes(_("Width")) ?>",
	"not-del-last-cell":				  "<?php echo addslashes(_("HTMLArea cowardly refuses to delete the last cell in row.")) ?>",
	"not-del-last-col":				  "<?php echo addslashes(_("HTMLArea cowardly refuses to delete the last column in table.")) ?>",
	"not-del-last-row":				  "<?php echo addslashes(_("HTMLArea cowardly refuses to delete the last row in table.")) ?>",
	"percent":					  "<?php echo addslashes(_("percent")) ?>",
	"pixels":					  "<?php echo addslashes(_("pixels")) ?>"
};
