</tbody>
</table>
<input type="hidden" name="actionID" value="" />
<input type="hidden" name="show" value="<?php echo htmlspecialchars(Util::getFormData('show', 'all')) ?>" />
<input type="hidden" name="sortby" value="<?php echo htmlspecialchars($sortby) ?>" />
<input type="hidden" name="sortdir" value="<?php echo htmlspecialchars($sortdir) ?>" />
<input type="hidden" name="key" value="<?php echo htmlspecialchars(Util::getFormData('key')) ?>" />
<input type="hidden" name="targetAddressbook" value="" />
<input type="hidden" name="targetList" value="" />
<input type="hidden" name="targetNew" value="" />
</form>
